### ISSUE TITLE
Version control within Bower

### ISSUE THREAD

**Issue by empurium** [jsimnz/nifty-modal#10]
I checked to see if a `bower install nifty.js` would get me the latest version with the .container removal, and it did. However I notice in my `bower.json`, the version to use is `"nifty-js": "nifty.js#*"`.

This means if nifty.js is used in production, every time the project is deployed, the latest copy of nifty.js is installed via `bower install`, and some of those changes may have affected my build without me knowing.

I've never set up a bower project, so I did some reading and found that the version control is actually pretty simple. You just make a tag of nifty.js with `git tag 0.2.1`, then push the new Tag to Github with `git push --tags`.

Then in your `nifty.js/bower.json`, you update the Version to point at the Tag you just created, so `0.2.1`. They require usage of "semver", which is Semantic Versioning, i.e. 3 octets: `0.2.1`.

Info about how Semver works (it's simple):
http://semver.org/

Some more info:
http://stackoverflow.com/questions/19456091/bower-register-new-version

So ultimately, I'm just wondering if you can create a `0.2.1` tag for nifty.js and update the `bower.json` so everybody can count on specific versions when they use it in their production builds? :)

`cd nifty.js`
`git tag 0.2.1`
`git push --tags`
`perl -pi -e 's/"version": "0.2"/"version": "0.2.1"/' bower.json`

Cheers!

**Comment by empurium** [comment]
Does this make sense? I'm happy to answer any questions, I'm actually pretty curious to see this in action.

**Comment by jsimnz** [comment]
Added a 0.2.0 tagged release, and updated the bower file.

All should be good now.

**Comment by empurium** [comment]
Do the changes have to be pushed up to Bower as well? I'm getting an error installing, looks like it still has 0.2, possibly on Bower's side:

`icharus :: ~/code/fs/freescan develop ✘ ✖✭% bower install --save nifty.js
bower nifty.js#*            not-cached git://github.com/jsimnz/nifty.js.git#*
bower nifty.js#*               resolve git://github.com/jsimnz/nifty.js.git#*
bower nifty.js#*              download https://github.com/jsimnz/nifty.js/archive/0.2.0.tar.gz
bower nifty.js#*               extract archive.tar.gz
bower nifty.js#*                 error Invalid Version: 0.2

Stack trace:
TypeError: Invalid Version: 0.2
    at new SemVer (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/semver/semver.js:273:11)
    at compare (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/semver/semver.js:460:10)
    at Object.neq (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/semver/semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:208:56)
    at GitHubResolver._savePkgMeta (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/core/resolvers/GitHubResolver.js:134:53)
    at _fulfilled (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
    at runSingle (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)

Console trace:
Error
    at StandardRenderer.error (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/renderers/StandardRenderer.js:83:37)
    at Logger.<anonymous> (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.7
Node version: 4.3.1
OS: Darwin 15.3.0 x64
`

**Comment by empurium** [comment]
Do these changes have to be pushed up to Bower as well? I'm getting an error on bower install nifty.js, seems like Bower still has the version with 0.2 in the bower.json:

icharus :: ~/code develop ✘ ✖✭% bower install --save nifty.js
bower nifty.js#\*            not-cached git://github.com/jsimnz/nifty.js.git#*
bower nifty.js#\*               resolve git://github.com/jsimnz/nifty.js.git#*
bower nifty.js#\*              download https://github.com/jsimnz/nifty.js/archive/0.2.0.tar.gz
bower nifty.js#\*               extract archive.tar.gz
bower nifty.js#\*                 error Invalid Version: 0.2

Stack trace:
TypeError: Invalid Version: 0.2
    at new SemVer (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/semver/semver.js:273:11)
    at compare (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/semver/semver.js:460:10)
    at Object.neq (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/semver/semver.js:504:10)
    at GitHubResolver.GitResolver._savePkgMeta (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:208:56)
    at GitHubResolver._savePkgMeta (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/core/resolvers/GitHubResolver.js:134:53)
    at _fulfilled (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
    at runSingle (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)

Console trace:
Error
    at StandardRenderer.error (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/renderers/StandardRenderer.js:83:37)
    at Logger.<anonymous> (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/Users/empurium/.nvm/versions/node/v4.3.1/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
System info:
Bower version: 1.7.7
Node version: 4.3.1
OS: Darwin 15.3.0 x64

**Comment by jsimnz** [comment]
I made the git tag, before I bumped the version in bower, so it was reading from the release tar.gz which still had the bower file at version 0.2.

Created a new release for version 0.2.1 which now aligns with bower. 

All systems go!
